name: Update Recent Activity
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_ACTIVITY_TOKEN }}
        with:
          GH_USERNAME: "kavania2002"
          COMMIT_EMAIL: "kavan155gondalia@gmail.com"
          COMMIT_MSG: "Update Recent Activity"
          MAX_LINES: 10
          COMMIT_NAME: "kavania2002"
